### ISSUE TITLE
gate 输入的一个问题

### ISSUE THREAD

**Issue by muzhailong** [tomtang110/Multitask#1]
老兄，task gate输入确定只使用task expert 不用shared expert吗？

**Comment by DiWang4data** [comment]
你是tang弟吗？为啥会给我发邮件




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月5日(星期四) 下午3:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [tomtang110/Multitask] gate 输入的一个问题 (#1)





 
老兄，task gate输入确定只使用task expert 不用shared expert吗？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by muzhailong** [comment]
github自动发邮件的吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月5日(周四) 下午4:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tomtang110/Multitask] gate 输入的一个问题 (#1)




 你是tang弟吗？为啥会给我发邮件 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2021年8月5日(星期四) 下午3:57 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;;  
 主题: [tomtang110/Multitask] gate 输入的一个问题 (#1) 
 
 
 
 
 
   
 老兄，task gate输入确定只使用task expert 不用shared expert吗？ 
   
 — 
 You are receiving this because you are subscribed to this thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tomtang110** [comment]
> 老兄，task gate输入确定只使用task expert 不用shared expert吗？
你说的哪个模型啊？
